### ISSUE TITLE
ODL SFC web 404 not found

### ISSUE THREAD

**Issue by akiskourtis** [trozet/sfc-random#3]
Greetings,
First of all kudos for the great work and effort.
I have successfully managed to run tacker sfc example.
Run the VNFs, created the chain, all outputs show that everything should be fine and working.

My only problem is that the url http://<ip>:8181/sfc/index.html outputs a 404 error.
The ODL url http://<ip>:8181/index.html works just fine

Could someone give a hint on where should I look, for errors, or at least which is the module of the sfc-ui that should be working properly?

At the apidoc/explorer/index.html url, I see various sfc urls, but cannot make out which would be the UI one.

Thank you,

Akis

**Comment by akiskourtis** [comment]
So after feature:install odl-sfc-ui 
from the karaf command line
The ODL web interface managed to have an SFC tab, which also successfully reflected the creation of the chains.

I would mark this issue as resolved.
If you feel this issue was trivial please feel free to delete it.

Thank you.

**Comment by trozet** [comment]
Hi Akis,
We purposely disable odl sfc ui in the latest patch as it conflicts with
the working sfc setup.   You can still use rest calls to determine what is
configured.   I will add those calls to this issue.

**Comment by akiskourtis** [comment]
Ok, great thank you for the info!

**Comment by ThomasJeffers** [comment]
> feature:install odl-sfc-ui

If that was the case so why in the [official docs](https://docs.opendaylight.org/projects/sfc/en/latest/user-guide.html) it says to install the feature odl-sfc-ui?
