### ISSUE TITLE
I get mySQL Errors during install

### ISSUE THREAD

**Issue by commapp** [trozet/sfc-random#5]
Hi,

Thanks for writing this code. I am trying to run this on a Liberty OSP 8 setup. I am getting the below errors during install.

Error: Could not prefetch mysql_database provider 'mysql': Execution of '/bin/mysql --defaults-extra-file=/root/.my.cnf -NBe show variables like '%_database' keystone' returned 1: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)
Error: Execution of '/bin/mysql --defaults-extra-file=/root/.my.cnf -NBe create database if not exists `tacker` character set `utf8` collate `utf8_general_ci`' returned 1: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)
Error: /Stage[main]/Tacker::Db::Mysql/Openstacklib::Db::Mysql[tacker]/Mysql_database[tacker]/ensure: change from absent to present failed: Execution of '/bin/mysql --defaults-extra-file=/root/.my.cnf -NBe create database if not exists `tacker` character set `utf8` collate `utf8_general_ci`' returned 1: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)
Notice: /Stage[main]/Tacker::Db::Mysql/Openstacklib::Db::Mysql[tacker]/Openstacklib::Db::Mysql::Host_access[tacker_172.16.0.10]/Mysql_user[tacker@172.16.0.10]: Dependency Mysql_database[tacker] has failures: true
Warning: /Stage[main]/Tacker::Db::Mysql/Openstacklib::Db::Mysql[tacker]/Openstacklib::Db::Mysql::Host_access[tacker_172.16.0.10]/Mysql_user[tacker@172.16.0.10]: Skipping because of failed dependencies
Notice: /Stage[main]/Tacker::Db::Mysql/Openstacklib::Db::Mysql[tacker]/Openstacklib::Db::Mysql::Host_access[tacker_%]/Mysql_user[tacker@%]: Dependency Mysql_database[tacker] has failures: true
Warning: /Stage[main]/Tacker::Db::Mysql/Openstacklib::Db::Mysql[tacker]/Openstacklib::Db::Mysql::Host_access[tacker_%]/Mysql_user[tacker@%]: Skipping because of failed dependencies
Error: Could not prefetch mysql_grant provider 'mysql': Execution of '/bin/mysql --defaults-extra-file=/root/.my.cnf -NBe SELECT CONCAT(User, '@',Host) AS User FROM mysql.user' returned 1: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)
Notice: /Stage[main]/Tacker::Db::Mysql/Openstacklib::Db::Mysql[tacker]/Openstacklib::Db::Mysql::Host_access[tacker_%]/Mysql_grant[tacker@%/tacker._]: Dependency Mysql_database[tacker] has failures: true
Warning: /Stage[main]/Tacker::Db::Mysql/Openstacklib::Db::Mysql[tacker]/Openstacklib::Db::Mysql::Host_access[tacker_%]/Mysql_grant[tacker@%/tacker._]: Skipping because of failed dependencies
Notice: /Stage[main]/Tacker::Db::Mysql/Openstacklib::Db::Mysql[tacker]/Openstacklib::Db::Mysql::Host_access[tacker_172.16.0.13]/Mysql_user[tacker@172.16.0.13]: Dependency Mysql_database[tacker] has failures: true
Warning: /Stage[main]/Tacker::Db::Mysql/Openstacklib::Db::Mysql[tacker]/Openstacklib::Db::Mysql::Host_access[tacker_172.16.0.13]/Mysql_user[tacker@172.16.0.13]: Skipping because of failed dependencies
Notice: /Stage[main]/Tacker::Db::Mysql/Openstacklib::Db::Mysql[tacker]/Openstacklib::Db::Mysql::Host_access[tacker_172.16.0.13]/Mysql_grant[tacker@172.16.0.13/tacker._]: Dependency Mysql_database[tacker] has failures: true
Warning: /Stage[main]/Tacker::Db::Mysql/Openstacklib::Db::Mysql[tacker]/Openstacklib::Db::Mysql::Host_access[tacker_172.16.0.13]/Mysql_grant[tacker@172.16.0.13/tacker._]: Skipping because of failed dependencies
Notice: /Stage[main]/Tacker::Db::Mysql/Openstacklib::Db::Mysql[tacker]/Openstacklib::Db::Mysql::Host_access[tacker_172.16.0.10]/Mysql_grant[tacker@172.16.0.10/tacker._]: Dependency Mysql_database[tacker] has failures: true
Warning: /Stage[main]/Tacker::Db::Mysql/Openstacklib::Db::Mysql[tacker]/Openstacklib::Db::Mysql::Host_access[tacker_172.16.0.10]/Mysql_grant[tacker@172.16.0.10/tacker._]: Skipping because of failed dependencies
Notice: /Stage[main]/Tacker::Db/Tacker_config[database/min_pool_size]/ensure: created
Notice: /Stage[main]/Tacker::Db/Tacker_config[database/max_pool_size]/ensure: created
Notice: /Stage[main]/Tacker::Db/Tacker_config[database/connection]/ensure: created
Notice: /Stage[main]/Tacker::Db/Tacker_config[database/max_retries]/ensure: created
Notice: /Stage[main]/Tacker::Db/Tacker_config[database/max_overflow]/ensure: created
Notice: /Stage[main]/Tacker::Db/Tacker_config[database/retry_interval]/ensure: created
Notice: /Stage[main]/Tacker::Db/Tacker_config[database/idle_timeout]/ensure: created
Notice: /Stage[main]/Tacker::Keystone::Auth/Keystone::Resource::Service_identity[tacker]/Keystone_service[tacker::servicevm]/ensure: created
Error: Execution of '/bin/openstack user create --format shell tacker --enable --password tacker --email tacker@localhost --domain Default' returned 1: Could not find resource Default
Error: /Stage[main]/Tacker::Keystone::Auth/Keystone::Resource::Service_identity[tacker]/Keystone_user[tacker]/ensure: change from absent to present failed: Execution of '/bin/openstack user create --format shell tacker --enable --password tacker --email tacker@localhost --domain Default' returned 1: Could not find resource Default
Notice: /Stage[main]/Tacker::Keystone::Auth/Keystone::Resource::Service_identity[tacker]/Keystone_user_role[tacker@service]: Dependency Keystone_user[tacker] has failures: true
Warning: /Stage[main]/Tacker::Keystone::Auth/Keystone::Resource::Service_identity[tacker]/Keystone_user_role[tacker@service]: Skipping because of failed dependencies
Error: Could not prefetch keystone_endpoint provider 'openstack': Execution of '/bin/openstack endpoint list --quiet --format csv' returned 1: An unexpected error prevented the server from fulfilling your request. (HTTP 500) (Request-ID: req-3acbf5c8-f0e3-47c2-9392-8dcf70676e4b)
Error: Execution of '/bin/openstack service list --quiet --format csv' returned 1: An unexpected error prevented the server from fulfilling your request. (HTTP 500) (Request-ID: req-683d15a8-1258-4d6e-909b-313cb089dc2e)
Error: /Stage[main]/Tacker::Keystone::Auth/Keystone::Resource::Service_identity[tacker]/Keystone_endpoint[regionOne/tacker::servicevm]/ensure: change from absent to present failed: Execution of '/bin/openstack service list --quiet --format csv' returned 1: An unexpected error prevented the server from fulfilling your request. (HTTP 500) (Request-ID: req-683d15a8-1258-4d6e-909b-313cb089dc2e)
Notice: /Stage[main]/Tacker/User[tacker]/ensure: created
Notice: /Stage[main]/Tacker/File[/var/lib/tacker]/ensure: created
Notice: /Stage[main]/Tacker/File[/var/log/tacker]/ensure: created
Notice: /Stage[main]/Tacker/File[/etc/tacker]/owner: owner changed 'root' to 'tacker'
Notice: /Stage[main]/Tacker/File[/etc/tacker]/group: group changed 'root' to 'tacker'
Notice: /Stage[main]/Tacker/File[/etc/tacker]/mode: mode changed '0755' to '0750'
Notice: /File[/etc/tacker]/seluser: seluser changed 'unconfined_u' to 'system_u'
Notice: /File[/etc/tacker]/seltype: seltype changed 'admin_home_t' to 'etc_t'
Notice: /Stage[main]/Tacker/File[/etc/tacker/tacker.conf]/owner: owner changed 'root' to 'tacker'
Notice: /Stage[main]/Tacker/File[/etc/tacker/tacker.conf]/group: group changed 'root' to 'tacker'
Notice: /Stage[main]/Tacker/File[/etc/tacker/tacker.conf]/mode: mode changed '0644' to '0600'
Notice: /File[/etc/tacker/tacker.conf]/seluser: seluser changed 'unconfined_u' to 'system_u'
Notice: /File[/etc/tacker/tacker.conf]/seltype: seltype changed 'admin_home_t' to 'etc_t'
Notice: /Stage[main]/Tacker/Tacker_config[keystone_authtoken/auth_url]/value: value changed 'http://127.0.0.1:35357' to 'http://192.168.126.136:35357'
Notice: /Stage[main]/Tacker::Db::Sync/Exec[tacker-manage db_sync]: Dependency Mysql_database[tacker] has failures: true
Warning: /Stage[main]/Tacker::Db::Sync/Exec[tacker-manage db_sync]: Skipping because of failed dependencies
Error: /Stage[main]/Tacker::Db::Sync/Exec[tacker-manage db_sync]: Failed to call refresh: Could not find command 'tacker-manage'
Error: /Stage[main]/Tacker::Db::Sync/Exec[tacker-manage db_sync]: Could not find command 'tacker-manage'
Notice: /Stage[main]/Tacker::Service/Service[tacker]: Dependency Mysql_database[tacker] has failures: true
Warning: /Stage[main]/Tacker::Service/Service[tacker]: Skipping because of failed dependencies
Notice: /Stage[main]/Tacker::Service/Service[tacker]: Triggered 'refresh' from 42 events

**Comment by commapp** [comment]
This is for installing tacker_config.sh

**Comment by trozet** [comment]
Hi, are you using the Apex installer?  We recently released a new version (Colorado 1.0) which includes Tacker already installed and you don't need to run this script.

**Comment by commapp** [comment]
No I was using the RedHat OSP Director. I used the bare tacker files and it installed up to a point where I can see it running on the dashboard.

I am closing this for now. Thanks for your reply!
